# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:16.3-alpine3.18
    command: "postgres -c config_file=/config/postgresql.conf"
    restart: always
    environment:
      POSTGRES_USER: "postgresadmin"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "postgresdb"
      PGDATA: "/data"
    ports:
    - 5000:5432
    volumes:
    - ./pgdata:/data
    - ./config:/config/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080